### ISSUE TITLE
Add to README.md a Quick Start section

### ISSUE THREAD

**Issue by ChristianBirchler** [cmbothwell/scrape-721#1]
# User Story
As a user, I want to start quickly with the tool so that I don't have to spend much time looking at the code.

# Acceptance Criteria
## Scenario 1
- Given: Repository is cloned, and dependencies are installed
- When: An Ethereum node is up and running
- Then: A quick start section of the `README.md` gives me the first hints on how to use the tool.

**Comment by cmbothwell** [comment]
Fixed via #0514e1e5caac8d744fa26448c08f3e3dbab18d1b.

**Comment by ChristianBirchler** [comment]
> Fixed via [0514e1e](https://github.com/cmbothwell/scrape-721/commit/0514e1e5caac8d744fa26448c08f3e3dbab18d1b)

Thank you very much!
